services:
  web:
    build: ./nginx
    container_name: transcendence-nginx
    ports:
      - "8443:443"
    volumes:
      - ./app:/var/www/html:ro
      - ./secrets/certs:/etc/nginx/certs:ro
    depends_on:
      - php
      - game-server
    networks:
      - appnet

  php:
    build: ./php
    container_name: transcendence-php
    volumes:
      - ./app:/var/www/html
      - ./sqlite_data:/var/www/sqlite
    environment:
      DB_PATH: /var/www/sqlite/transcendence.sqlite
    networks:
      - appnet

  game-server:
    build: ./game-server
    container_name: transcendence-game-server
    networks:
      - appnet
    expose:
      - "3000"

networks:
  appnet:
    driver: bridge
